=== maxsnax/SpyParty-Major-League/App_Data/Seasons.xsd
<?xml version="1.0" encoding="UTF-8"?>
<!-- Author: Thomas Martin -->
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">

	<!-- Definition of a simple type for display name -->
	<xs:simpleType name="string">
		<xs:restriction base="xs:string">
			<xs:minLength value="1"/>
			<xs:maxLength value="50"/>
		</xs:restriction>
	</xs:simpleType>

	<!-- Definition of the root element -->
	<xs:element name="Seasons">
		<xs:complexType>
			<xs:sequence>
				<xs:element name="Season" maxOccurs="unbounded">
					<xs:complexType>
						<xs:sequence>
							<!-- Name of the season -->
							<xs:element name="Name" type="string"/>
							<!-- Definition of ranks within a season -->
							<xs:element name="Rank" maxOccurs="unbounded">
								<xs:complexType>
									<xs:sequence>
										<!-- Name of the rank -->
										<xs:element name="Name" type="string"/>
										<!-- Definition of players within a rank -->
										<xs:element name="Player" maxOccurs="unbounded">
											<xs:complexType>
												<xs:sequence>
													<!-- DisplayName element -->
													<xs:element name="DisplayName" type="string"/>
													<!-- status element-->
													<xs:element name="Status" type="string"></xs:element>
													<!-- PlayerID element -->
													<xs:element name="PlayerID" type="string"/>
												</xs:sequence>
											</xs:complexType>
										</xs:element>
									</xs:sequence>
								</xs:complexType>
							</xs:element>
						</xs:sequence>
					</xs:complexType>
				</xs:element>
			</xs:sequence>
		</xs:complexType>
	</xs:element>

</xs:schema>

=== maxsnax/SpyParty-Major-League/App_Data/Seasons.xml
<?xml version="1.0" encoding="UTF-8"?>

<Seasons xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="Seasons.xsd">

	<!-- ========================================================================================================================== -->
	<!-- Season 1 -->
	<!-- ========================================================================================================================== -->

	<Season>
		<Name>SML Season 1</Name>
		<Rank>
			<Name>Grandmaster</Name>
			<Player>
				<DisplayName>Nebula</DisplayName>
				<Status>Active</Status>
				<PlayerID>1</PlayerID>
			</Player>
			<Player>
				<DisplayName>Rov</DisplayName>
				<Status>Active</Status>
				<PlayerID>2</PlayerID>
			</Player>
			<Player>
				<DisplayName>OpiWrites</DisplayName>
				<Status>Active</Status>
				<PlayerID>1</PlayerID>
			</Player>
			<Player>
				<DisplayName>Sauerkraut</DisplayName>
				<Status>Active</Status>
				<PlayerID>1</PlayerID>
			</Player>
			<Player>
				<DisplayName>Miniorek</DisplayName>
				<Status>Active</Status>
				<PlayerID>1</PlayerID>
			</Player>
			<Player>
				<DisplayName>Pofke</DisplayName>
				<Status>Active</Status>
				<PlayerID>1</PlayerID>
			</Player>
			<Player>
				<DisplayName>Turnipboy</DisplayName>
				<Status>Active</Status>
				<PlayerID>1</PlayerID>
			</Player>
			<Player>
				<DisplayName>Koopa</DisplayName>
				<Status>Forfeit</Status>
				<PlayerID>1</PlayerID>
			</Player>
			<!-- Add more players as needed -->
		</Rank>
		<Rank>
			<Name>Master</Name>
			<Player>
				<DisplayName>Adafheyesh</DisplayName>
				<Status>Active</Status>
				<PlayerID>3</PlayerID>
			</Player>
			<Player>
				<DisplayName>Dampsquib</DisplayName>
				<Status>Active</Status>
				<PlayerID>4</PlayerID>
			</Player>
			<Player>
				<DisplayName>C-RAMS</DisplayName>
				<Status>Active</Status>
				<PlayerID>1</PlayerID>
			</Player>
			<Player>
				<DisplayName>Sheph</DisplayName>
				<Status>Active</Status>
				<PlayerID>1</PlayerID>
			</Player>
			<Player>
				<DisplayName>Martini</DisplayName>
				<Status>Active</Status>
				<PlayerID>1</PlayerID>
			</Player>
			<Player>
				<DisplayName>Zerodoom</DisplayName>
				<Status>Active</Status>
				<PlayerID>1</PlayerID>
			</Player>
			<Player>
				<DisplayName>Monaters</DisplayName>
				<Status>Forfeit</Status>
				<PlayerID>1</PlayerID>
			</Player>
			<Player>
				<DisplayName>Pwndnoob</DisplayName>
				<Status>Forfeit</Status>
				<PlayerID>1</PlayerID>
			</Player>
			<!-- Add more players as needed -->
		</Rank>
		<Rank>
			<Name>Ruby</Name>
			<Player>
				<DisplayName>Wrestler</DisplayName>
				<Status>Active</Status>
				<PlayerID>3</PlayerID>
			</Player>
			<Player>
				<DisplayName>Graash</DisplayName>
				<Status>Active</Status>
				<PlayerID>4</PlayerID>
			</Player>
			<Player>
				<DisplayName>Guggie</DisplayName>
				<Status>Active</Status>
				<PlayerID>1</PlayerID>
			</Player>
			<Player>
				<DisplayName>Nanthelas</DisplayName>
				<Status>Active</Status>
				<PlayerID>1</PlayerID>
			</Player>
			<Player>
				<DisplayName>Banana Bread</DisplayName>
				<Status>Active</Status>
				<PlayerID>1</PlayerID>
			</Player>
			<Player>
				<DisplayName>Beanie</DisplayName>
				<Status>Active</Status>
				<PlayerID>1</PlayerID>
			</Player>
			<Player>
				<DisplayName>Slappydavis</DisplayName>
				<Status>Active</Status>
				<PlayerID>1</PlayerID>
			</Player>
			<Player>
				<DisplayName>DavidW</DisplayName>
				<Status>Forfeit</Status>
				<PlayerID>1</PlayerID>
			</Player>
			<!-- Add more players as needed -->
		</Rank>
		<Rank>
			<Name>Emerald</Name>
			<Player>
				<DisplayName>Scout</DisplayName>
				<Status>Active</Status>
				<PlayerID>3</PlayerID>
			</Player>
			<Player>
				<DisplayName>Hunu</DisplayName>
				<Status>Active</Status>
				<PlayerID>4</PlayerID>
			</Player>
			<Player>
				<DisplayName>AstatineEffect</DisplayName>
				<Status>Active</Status>
				<PlayerID>1</PlayerID>
			</Player>
			<Player>
				<DisplayName>Verdruss</DisplayName>
				<Status>Active</Status>
				<PlayerID>1</PlayerID>
			</Player>
			<Player>
				<DisplayName>Sykosloth</DisplayName>
				<Status>Active</Status>
				<PlayerID>1</PlayerID>
			</Player>
			<Player>
				<DisplayName>gENTleman</DisplayName>
				<Status>Active</Status>
				<PlayerID>1</PlayerID>
			</Player>
			<Player>
				<DisplayName>iggythegrifter</DisplayName>
				<Status>Active</Status>
				<PlayerID>1</PlayerID>
			</Player>
			<Player>
				<DisplayName>June</DisplayName>
				<Status>Forfeit</Status>
				<PlayerID>1</PlayerID>
			</Player>
			<!-- Add more players as needed -->
		</Rank>
		<Rank>
			<Name>Sapphire</Name>
			<Player>
				<DisplayName>Calamay</DisplayName>
				<Status>Active</Status>
				<PlayerID>3</PlayerID>
			</Player>
			<Player>
				<DisplayName>Hornet</DisplayName>
				<Status>Active</Status>
				<PlayerID>4</PlayerID>
			</Player>
			<Player>
				<DisplayName>Roxo</DisplayName>
				<Status>Active</Status>
				<PlayerID>1</PlayerID>
			</Player>
			<Player>
				<DisplayName>Catnip</DisplayName>
				<Status>Active</Status>
				<PlayerID>1</PlayerID>
			</Player>
			<Player>
				<DisplayName>Yosh</DisplayName>
				<Status>Active</Status>
				<PlayerID>1</PlayerID>
			</Player>
			<Player>
				<DisplayName>AiCoVT</DisplayName>
				<Status>Active</Status>
				<PlayerID>1</PlayerID>
			</Player>
			<Player>
				<DisplayName>Lavinuke</DisplayName>
				<Status>Active</Status>
				<PlayerID>1</PlayerID>
			</Player>
			<Player>
				<DisplayName>BYE</DisplayName>
				<Status>Active</Status>
				<PlayerID>1</PlayerID>
			</Player>
			<!-- Add more players as needed -->
		</Rank>
		<Rank>
			<Name>Topaz</Name>
			<Player>
				<DisplayName>OneHoppingBunny</DisplayName>
				<Status>Active</Status>
				<PlayerID>3</PlayerID>
			</Player>
			<Player>
				<DisplayName>bloodredyeti</DisplayName>
				<Status>Active</Status>
				<PlayerID>4</PlayerID>
			</Player>
			<Player>
				<DisplayName>iSkate4PlanB</DisplayName>
				<Status>Forfeit</Status>
				<PlayerID>1</PlayerID>
			</Player>
			<Player>
				<DisplayName>Coding</DisplayName>
				<Status>Forfeit</Status>
				<PlayerID>1</PlayerID>
			</Player>
			<!-- Add more players as needed -->
		</Rank>
	</Season>

	<!-- ========================================================================================================================== -->
	<!-- Season 2 -->
	<!-- ========================================================================================================================== -->
	
	<Season>
		<Name>SML Season 2</Name>
		<Rank>
			<Name>Grandmaster</Name>
			<Player>
				<DisplayName>Nebula</DisplayName>
				<Status>Active</Status>
				<PlayerID>1</PlayerID>
			</Player>
			<Player>
				<DisplayName>Rov</DisplayName>
				<Status>Active</Status>
				<PlayerID>2</PlayerID>
			</Player>
			<Player>
				<DisplayName>OpiWrites</DisplayName>
				<Status>Active</Status>
				<PlayerID>1</PlayerID>
			</Player>
			<Player>
				<DisplayName>Sauerkraut</DisplayName>
				<Status>Active</Status>
				<PlayerID>1</PlayerID>
			</Player>
			<Player>
				<DisplayName>Miniorek</DisplayName>
				<Status>Active</Status>
				<PlayerID>1</PlayerID>
			</Player>
			<Player>
				<DisplayName>Pofke</DisplayName>
				<Status>Active</Status>
				<PlayerID>1</PlayerID>
			</Player>
			<Player>
				<DisplayName>Turnipboy</DisplayName>
				<Status>Active</Status>
				<PlayerID>1</PlayerID>
			</Player>
			<!-- Add more players as needed -->
		</Rank>
		<Rank>
			<Name>Master</Name>
			<Player>
				<DisplayName>Adafheyesh</DisplayName>
				<Status>Active</Status>
				<PlayerID>3</PlayerID>
			</Player>
			<Player>
				<DisplayName>Dampsquib</DisplayName>
				<Status>Active</Status>
				<PlayerID>4</PlayerID>
			</Player>
			<Player>
				<DisplayName>C-RAMS</DisplayName>
				<Status>Active</Status>
				<PlayerID>1</PlayerID>
			</Player>
			<Player>
				<DisplayName>Sheph</DisplayName>
				<Status>Active</Status>
				<PlayerID>1</PlayerID>
			</Player>
			<Player>
				<DisplayName>Martini</DisplayName>
				<Status>Active</Status>
				<PlayerID>1</PlayerID>
			</Player>
			<Player>
				<DisplayName>Zerodoom</DisplayName>
				<Status>Active</Status>
				<PlayerID>1</PlayerID>
			</Player>
			<Player>
				<DisplayName>Monaters</DisplayName>
				<Status>Active</Status>
				<PlayerID>1</PlayerID>
			</Player>
			<!-- Add more players as needed -->
		</Rank>
		<Rank>
			<Name>Ruby</Name>
			<Player>
				<DisplayName>Wrestler</DisplayName>
				<Status>Active</Status>
				<PlayerID>3</PlayerID>
			</Player>
			<Player>
				<DisplayName>Graash</DisplayName>
				<Status>Active</Status>
				<PlayerID>4</PlayerID>
			</Player>
			<Player>
				<DisplayName>Guggie</DisplayName>
				<Status>Active</Status>
				<PlayerID>1</PlayerID>
			</Player>
			<Player>
				<DisplayName>Nanthelas</DisplayName>
				<Status>Active</Status>
				<PlayerID>1</PlayerID>
			</Player>
			<Player>
				<DisplayName>Banana Bread</DisplayName>
				<Status>Active</Status>
				<PlayerID>1</PlayerID>
			</Player>
			<Player>
				<DisplayName>Beanie</DisplayName>
				<Status>Active</Status>
				<PlayerID>1</PlayerID>
			</Player>
			<Player>
				<DisplayName>Slappydavis</DisplayName>
				<Status>Active</Status>
				<PlayerID>1</PlayerID>
			</Player>
			<!-- Add more players as needed -->
		</Rank>
		<Rank>
			<Name>Emerald</Name>
			<Player>
				<DisplayName>Scout</DisplayName>
				<Status>Active</Status>
				<PlayerID>3</PlayerID>
			</Player>
			<Player>
				<DisplayName>Hunu</DisplayName>
				<Status>Active</Status>
				<PlayerID>4</PlayerID>
			</Player>
			<Player>
				<DisplayName>AstatineEffect</DisplayName>
				<Status>Active</Status>
				<PlayerID>1</PlayerID>
			</Player>
			<Player>
				<DisplayName>Verdruss</DisplayName>
				<Status>Active</Status>
				<PlayerID>1</PlayerID>
			</Player>
			<Player>
				<DisplayName>Sykosloth</DisplayName>
				<Status>Active</Status>
				<PlayerID>1</PlayerID>
			</Player>
			<Player>
